### ISSUE TITLE
test failure causes all test to fail

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/angela#24]
If one test times out (junit rule), then all the test fails with:
```
java.lang.RuntimeException: Error starting agent localhost

	at org.terracotta.angela.agent.Agent$Node.init(Agent.java:202)
	at org.terracotta.angela.agent.Agent$Node.<init>(Agent.java:122)
	at org.terracotta.angela.agent.Agent$Node.<init>(Agent.java:117)
	at org.terracotta.angela.client.ClusterFactory.init(ClusterFactory.java:139)
	at org.terracotta.angela.client.ClusterFactory.tsa(ClusterFactory.java:208)
	at org.terracotta.dynamic_config.test_support.DynamicConfigIT.before(DynamicConfigIT.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.terracotta.dynamic_config.test_support.util.NodeOutputRule$1.evaluate(NodeOutputRule.java:60)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: class org.apache.ignite.IgniteException: Ignite instance with this name has already been started: localhost
	at org.apache.ignite.internal.util.IgniteUtils.convertException(IgniteUtils.java:1029)
	at org.apache.ignite.Ignition.start(Ignition.java:326)
	at org.terracotta.angela.agent.Agent$Node.init(Agent.java:199)
	... 20 more
Caused by: class org.apache.ignite.IgniteCheckedException: Ignite instance with this name has already been started: localhost
	at org.apache.ignite.internal.IgnitionEx.start0(IgnitionEx.java:1143)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:678)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:603)
	at org.apache.ignite.Ignition.start(Ignition.java:323)
	... 21 more

```

**Comment by saurabhagas** [comment]
Relates to the fact that there's only ignite instance per host, and also with the work that @aurbroszniowski was doing to make angela run tests concurrently. Unassigning myself from the issue.

**Comment by mathieucarbou** [comment]
Implementing a fix in https://github.com/Terracotta-OSS/terracotta-platform/pull/678 and will soon extract a AngelaRule from what we have in tc-platform (work already done at 80%).

**Comment by mathieucarbou** [comment]
resolved
