### ISSUE TITLE
Angela kit copy in angela/kits is loosing file attributes

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/angela#27]
I have upgraded to 3.0.15 and get this error:

```
class org.apache.ignite.IgniteException: Remote job threw user exception (override or implement ComputeTask.result(..) method if you would like to have automatic failover for this exception): Failed to execute job due to unexpected runtime exception [jobId=33a42140171-c2aa1600-661c-4f51-a7ae-05e689db602e, ses=GridJobSessionImpl [ses=GridTaskSessionImpl [taskName=org.terracotta.angela.client.Tsa$$Lambda$106/1941847582, dep=GridDeployment [ts=1584911242976, depMode=SHARED, clsLdr=sun.misc.Launcher$AppClassLoader@18b4aac2, clsLdrId=e8542140171-7b466052-abc9-46a9-b30f-45d4bce20336, userVer=0, loc=true, sampleClsName=org.terracotta.angela.common.util.IgniteCommonHelper, pendingUndeploy=false, undeployed=false, usage=1], taskClsName=org.terracotta.angela.client.Tsa$$Lambda$106/1941847582, sesId=23a42140171-c2aa1600-661c-4f51-a7ae-05e689db602e, startTime=1584911244387, endTime=9223372036854775807, taskNodeId=c2aa1600-661c-4f51-a7ae-05e689db602e, clsLdr=sun.misc.Launcher$AppClassLoader@18b4aac2, closed=false, cpSpi=null, failSpi=null, loadSpi=null, usage=1, fullSup=false, internal=false, topPred=null, subjId=c2aa1600-661c-4f51-a7ae-05e689db602e, mapFut=IgniteFuture [orig=GridFutureAdapter [ignoreInterrupts=false, state=INIT, res=null, hash=144814010]], execName=null], jobId=33a42140171-c2aa1600-661c-4f51-a7ae-05e689db602e], err=Cannot start process [/Users/mathieu/workspace/terracotta/terracotta-platform/dynamic-config/testing/system-tests/target/angela/kits/5.7-SNAPSHOT/platform-kit-5.7-SNAPSHOT/server/bin/start-tc-server.sh, --node-repository-dir, terracotta1-1/repository, -f, /Users/matc/workspace/terracotta/terracotta-platform/dynamic-config/testing/system-tests/target/test-data/1584911238204-3376473518706484161/single-stripe.properties]]

	at org.apache.ignite.compute.ComputeTaskAdapter.result(ComputeTaskAdapter.java:102)
	at org.apache.ignite.internal.processors.task.GridTaskWorker$5.apply(GridTaskWorker.java:1053)
	at org.apache.ignite.internal.processors.task.GridTaskWorker$5.apply(GridTaskWorker.java:1046)
	at org.apache.ignite.internal.util.IgniteUtils.wrapThreadLoader(IgniteUtils.java:6852)
	at org.apache.ignite.internal.processors.task.GridTaskWorker.result(GridTaskWorker.java:1046)
	at org.apache.ignite.internal.processors.task.GridTaskWorker.onResponse(GridTaskWorker.java:864)
	at org.apache.ignite.internal.processors.task.GridTaskProcessor.processJobExecuteResponse(GridTaskProcessor.java:1081)
	at org.apache.ignite.internal.processors.task.GridTaskProcessor$JobMessageListener.onMessage(GridTaskProcessor.java:1316)
	at org.apache.ignite.internal.managers.communication.GridIoManager.invokeListener(GridIoManager.java:1569)
	at org.apache.ignite.internal.managers.communication.GridIoManager.processRegularMessage0(GridIoManager.java:1197)
	at org.apache.ignite.internal.managers.communication.GridIoManager.access$4200(GridIoManager.java:127)
	at org.apache.ignite.internal.managers.communication.GridIoManager$9.run(GridIoManager.java:1093)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: class org.apache.ignite.compute.ComputeUserUndeclaredException: Failed to execute job due to unexpected runtime exception [jobId=33a42140171-c2aa1600-661c-4f51-a7ae-05e689db602e, ses=GridJobSessionImpl [ses=GridTaskSessionImpl [taskName=org.terracotta.angela.client.Tsa$$Lambda$106/1941847582, dep=GridDeployment [ts=1584911242976, depMode=SHARED, clsLdr=sun.misc.Launcher$AppClassLoader@18b4aac2, clsLdrId=e8542140171-7b466052-abc9-46a9-b30f-45d4bce20336, userVer=0, loc=true, sampleClsName=org.terracotta.angela.common.util.IgniteCommonHelper, pendingUndeploy=false, undeployed=false, usage=1], taskClsName=org.terracotta.angela.client.Tsa$$Lambda$106/1941847582, sesId=23a42140171-c2aa1600-661c-4f51-a7ae-05e689db602e, startTime=1584911244387, endTime=9223372036854775807, taskNodeId=c2aa1600-661c-4f51-a7ae-05e689db602e, clsLdr=sun.misc.Launcher$AppClassLoader@18b4aac2, closed=false, cpSpi=null, failSpi=null, loadSpi=null, usage=1, fullSup=false, internal=false, topPred=null, subjId=c2aa1600-661c-4f51-a7ae-05e689db602e, mapFut=IgniteFuture [orig=GridFutureAdapter [ignoreInterrupts=false, state=INIT, res=null, hash=144814010]], execName=null], jobId=33a42140171-c2aa1600-661c-4f51-a7ae-05e689db602e], err=Cannot start process [/Users/mathieu/workspace/terracotta/terracotta-platform/dynamic-config/testing/system-tests/target/angela/kits/5.7-SNAPSHOT/platform-kit-5.7-SNAPSHOT/server/bin/start-tc-server.sh, --node-repository-dir, terracotta1-1/repository, -f, /Users/matc/workspace/terracotta/terracotta-platform/dynamic-config/testing/system-tests/target/test-data/1584911238204-3376473518706484161/single-stripe.properties]]
	at org.apache.ignite.internal.processors.job.GridJobWorker.handleThrowable(GridJobWorker.java:689)
	at org.apache.ignite.internal.processors.job.GridJobWorker.execute0(GridJobWorker.java:621)
	at org.apache.ignite.internal.processors.job.GridJobWorker.body(GridJobWorker.java:491)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:120)
	at org.apache.ignite.internal.processors.job.GridJobProcessor.processJobExecuteRequest(GridJobProcessor.java:1191)
	at org.apache.ignite.internal.processors.job.GridJobProcessor$JobExecutionListener.onMessage(GridJobProcessor.java:1923)
	... 7 more
Caused by: java.lang.RuntimeException: Cannot start process [/Users/mathieu/workspace/terracotta/terracotta-platform/dynamic-config/testing/system-tests/target/angela/kits/5.7-SNAPSHOT/platform-kit-5.7-SNAPSHOT/server/bin/start-tc-server.sh, --node-repository-dir, terracotta1-1/repository, -f, /Users/matc/workspace/terracotta/terracotta-platform/dynamic-config/testing/system-tests/target/test-data/1584911238204-3376473518706484161/single-stripe.properties]
	at org.terracotta.angela.common.distribution.WatchedProcess.<init>(WatchedProcess.java:38)
	at org.terracotta.angela.common.distribution.Distribution107Controller.createTsa(Distribution107Controller.java:106)
	at org.terracotta.angela.common.TerracottaServerInstance.create(TerracottaServerInstance.java:93)
	at org.terracotta.angela.agent.AgentController.createTsa(AgentController.java:279)
	at org.terracotta.angela.client.Tsa.lambda$create$4baf3c22$1(Tsa.java:227)
	at org.apache.ignite.internal.processors.closure.GridClosureProcessor$C4.execute(GridClosureProcessor.java:1944)
	at org.apache.ignite.internal.processors.job.GridJobWorker$2.call(GridJobWorker.java:568)
	at org.apache.ignite.internal.util.IgniteUtils.wrapThreadLoader(IgniteUtils.java:6820)
	at org.apache.ignite.internal.processors.job.GridJobWorker.execute0(GridJobWorker.java:562)
	... 11 more
Caused by: org.zeroturnaround.exec.ProcessInitException: Could not execute [/Users/mathieu/workspace/terracotta/terracotta-platform/dynamic-config/testing/system-tests/target/angela/kits/5.7-SNAPSHOT/platform-kit-5.7-SNAPSHOT/server/bin/start-tc-server.sh, --node-repository-dir, terracotta1-1/repository, -f, /Users/matc/workspace/terracotta/terracotta-platform/dynamic-config/testing/system-tests/target/test-data/1584911238204-3376473518706484161/single-stripe.properties] in /Users/mathieu/workspace/terracotta/terracotta-platform/dynamic-config/testing/system-tests/target/angela/work/DiagnosticIT-20200322-090718-0-tsa/5.7-SNAPSHOT with environment {JAVA_HOME=/Users/matc/.jenv/versions/1.8, JAVA_OPTS=-Djdk.security.allowNonCaAnchor=false}. Error=13, Permission denied
	at org.zeroturnaround.exec.ProcessInitException.newInstance(ProcessInitException.java:80)
	at org.zeroturnaround.exec.ProcessExecutor.invokeStart(ProcessExecutor.java:1002)
	at org.zeroturnaround.exec.ProcessExecutor.startInternal(ProcessExecutor.java:970)
	at org.zeroturnaround.exec.ProcessExecutor.start(ProcessExecutor.java:942)
	at org.terracotta.angela.common.distribution.WatchedProcess.<init>(WatchedProcess.java:36)
	... 19 more
Caused by: java.io.IOException: Cannot run program "/Users/mathieu/workspace/terracotta/terracotta-platform/dynamic-config/testing/system-tests/target/angela/kits/5.7-SNAPSHOT/platform-kit-5.7-SNAPSHOT/server/bin/start-tc-server.sh" (in directory "/Users/mathieu/workspace/terracotta/terracotta-platform/dynamic-config/testing/system-tests/target/angela/work/DiagnosticIT-20200322-090718-0-tsa/5.7-SNAPSHOT"): error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.zeroturnaround.exec.ProcessExecutor.invokeStart(ProcessExecutor.java:997)
	... 22 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 23 more
```

Angela is loosing file attributes when copying the kit that we have unpacked with Maven:

```
~/.../terracotta/terracotta-platform ( angela {4} U:1 ⊘ )
❯  cd dynamic-config/testing/system-tests/
/Users/matc/workspace/terracotta/terracotta-platform/dynamic-config/testing/system-tests

~/.../testing/system-tests ( angela {4} U:1 ⊘ )
❯  ls -al target/platform-kit-5.7-SNAPSHOT/server/bin/
total 16
drwxr-xr-x  4 matc  staff   128 Mar 22 17:06 .
drwxr-xr-x  5 matc  staff   160 Mar 22 17:06 ..
-rwxrwxr-x  1 matc  staff  2306 Mar 18 20:00 start-tc-server.bat
-rwxrwxr-x  1 matc  staff  2182 Mar 18 20:00 start-tc-server.sh

~/.../testing/system-tests ( angela {4} U:1 ⊘ )
❯  ls -al target/angela/kits/5.7-SNAPSHOT/platform-kit-5.7-SNAPSHOT/server/bin/
total 16
drwxr-xr-x  4 matc  staff   128 Mar 22 17:07 .
drwxr-xr-x  5 matc  staff   160 Mar 22 17:07 ..
-rw-r--r--  1 matc  staff  2306 Mar 22 17:07 start-tc-server.bat
-rw-r--r--  1 matc  staff  2182 Mar 22 17:07 start-tc-server.sh
```

**Comment by saurabhagas** [comment]
Done
