### ISSUE TITLE
Angela not stopping if test times out

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/angela#29]
You can reproduce by running the tests in PR: https://github.com/Terracotta-OSS/terracotta-platform/pull/609

basically, the test times out:

```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds

	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at org.apache.ignite.internal.util.future.GridFutureAdapter.get0(GridFutureAdapter.java:178)
	at org.apache.ignite.internal.util.future.GridFutureAdapter.get(GridFutureAdapter.java:141)
	at org.apache.ignite.internal.util.future.IgniteFutureImpl.get(IgniteFutureImpl.java:134)
	at org.terracotta.angela.client.util.IgniteClientHelper.executeRemotely(IgniteClientHelper.java:62)
	at org.terracotta.angela.client.ConfigTool.executeCommand(ConfigTool.java:44)
	at org.terracotta.dynamic_config.test_support.DynamicConfigIT.configToolInvocation(DynamicConfigIT.java:441)
	at org.terracotta.dynamic_config.system_tests.activated.AttachCommand1x3IT.test_attach_to_activated_cluster_with_offline_node(AttachCommand1x3IT.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.terracotta.dynamic_config.test_support.util.NodeOutputRule$1.evaluate(NodeOutputRule.java:60)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

When that happens, all server process are not shutdown:

```
~/.../terracotta/terracotta-platform ( attach {4} U:1 ⊘ )
❯  jps
13218 Launcher
13556 TCServerMain
13253 TCServerMain
1397 
13704 Jps
12472 TCServerMain
11707 GradleDaemon
```

**Comment by mathieucarbou** [comment]
You can use that to create a timeout:
```
  public AttachCommand1x3IT() {
    super(Duration.ofSeconds(60));
  }
```

**Comment by aurbroszniowski** [comment]
This is a normal behaviour.
If timeout are expected to occur in a test, the test should have a shutdown mechanism to do the cleanup when timing out. Angela (or any framework) can not clean up in this kind of case when the JVM is abruptly killed, this reponsibility should be at the test level.

We can try to add a shutdownHook to the Angela Clusterfactory, in order to stop all external processes, eventhough this is not expected to be taken into account in certain cases.
This can maybe give some inspiration:
https://github.com/schnatterer/JUnitShutdown/blob/master/src/test/java/info/schnatterer/test/shutdown/JUnitShutdown.java

**Comment by mathieucarbou** [comment]
ok so I am CC-ing some people so that they are aware of this issue because it can cause problems for jenkins build / pr buidls / etc.

@cljohnso @chrisdennis @akomakom @myronkscott 

FYI in case of a test timeout, at the moment there is no provided Junit integration by angela to do a proper shutdown of the servers. So we might have some processes kept in memory which can impact subsequent tests.

**Comment by mathieucarbou** [comment]
Implementing a fix in https://github.com/Terracotta-OSS/terracotta-platform/pull/678 and will soon extract a AngelaRule from what we have in tc-platform (work already done at 80%).

**Comment by saurabhagas** [comment]
Fixed with the introduction of AngelaRule

**Comment by mathieucarbou** [comment]
resolved
